#!/bin/bash

b=` echo $1 | awk -F '[.]' '{print $1}'`

grep  "energy   new            ="  $1 | nl  -s '     ' >$b.dat

a=`grep -h -m 1 "     energy   new            ="  $1 | awk -F '[=]' '{print $2}' | sed 's/ Ry//g'`

cat > $b.gpl << EOF
set term postscript color enhanced "Helvetica" 20

set pointsize 1.4 
set key Left reverse

set mxtics 2
set mytics 2

set ylabel "{/Helvetica-Bold=24 energy/kj.mol^{-1}"

set xrange[*:*]
set yrange[*:*]

set output "$b.ps"
set key at graph 0.95, graph 0.45 vertical maxrows 7
set xlabel "number of cycles" 

ry2kjmol=1312.749808738665

set label 1  "" at graph 0.16, graph 0.85
plot   "$b.dat" index 0 u 1:(\$5-$a)*ry2kjmol w l lw 4 lc rgb "black" ti "" 
EOF

gnuplot $b.gpl 
evince $b.ps 
