#!/bin/bash

c=` echo $1 | awk -F '[.]' '{print $1}'`

a=`grep -A 2 -m 1 " Current geometry (xyz format, in Angstrom)" $c.out | sed '1,2d'`
a=$[$a+3]

grep -A $a " Current geometry (xyz format, in Angstrom)" $c.out > $c-wx-out.dat

sed -i '/ Current geometry (xyz format, in Angstrom)/d' $c-wx-out.dat
sed -i '/--/d' $c-wx-out.dat
sed -i '/^$/d' $c-wx-out.dat

grep " ENERGY=" $c-wx-out.dat | awk -F '[=]' '{print $2}' | nl  -s '     ' > $c-out-energy.dat

b=`grep -m 1 " ENERGY=" $c-wx-out.dat | awk -F '[=]' '{print $2}'`

cat > $c-out.gpl << EOF
set term postscript color enhanced "Helvetica" 20

set pointsize 1.4 

set ylabel "{/Helvetica-Bold=24 energy/kJ mol^{-1}}"
set format x "%.1f"
set format y "%.1f"
Eh2kcmol =  627.509438586222
Eh2kjmol =  2625.49961747733

set xrange[*:*]
set yrange[*:*]

set output "$c-out.ps"
set key at graph 0.95, graph 0.45 vertical maxrows 7
set xlabel "Steps-of-interation"

set label 1  "" at graph 0.16, graph 0.85
plot   "$c-out-energy.dat" index 0 u 1:(\$2-$b)*Eh2kjmol w lp lw 4 pt 7 lc rgb "black" ti ""
EOF


wxmacmolplt $c-wx-out.dat &
gnuplot $c-out.gpl &
atril $c-out.ps &
